### PR TITLE
Add Gradle support

### PR DESCRIPTION
**Pull request by marcoRS**
This adds Gradle support and structures the project in the way it is typically structure by AS when starting a new project. 

I also recommend https://jitpack.io/ for publication.

### CODE REVIEW

**Comment by marcoRS** [comment]
@sandisk-opensource  Any thoughts on this?

**Comment by sandisk-opensource** [comment]
Marco – thanks for the message. Sivaraj is the maintainer and should be able to answer this request.

Thank You,
Nithya A. Ruff,  Director, SanDisk Open Source Strategy Office
WIN Board Member
SanDisk Corporation
951 SanDisk Drive, Milpitas, CA 95035
T: + (408-801-7068)| M: + (510-378-3159)
Nithya.Ruff@SanDisk.commailto:Nithya.Ruff@SanDisk.com        Twitter: @nithyaruffhttps://twitter.com/nithyaruff

**Comment by sivarajsandisk** [comment]
Macro - It seems Jitpack is a cool tool to create the artifacts. Do you have any idea what kind of license is being used by Jitpack for Open source projects? I could not find a license file in their repository.

**Comment by marcoRS** [comment]
@sivarajsandisk I'm unsure about the license. I was unable to find further information on their site.

**Comment by jitpack-io** [comment]
Hi all,
Open source projects on JitPack keep their own license for build artifacts (aar,jar). Looks like it's Apache 2 in your case. More details in [Terms](https://jitpack.io/w/terms.html)

**Comment by sivarajsandisk** [comment]
@jitpack-io  In that case, if someone uses the artifacts of RealPathStorageLibrary generated by Jitpack, the license to use tat artifact will be Apache 2, Right?

**Comment by jitpack-io** [comment]
@sivarajsandisk That's right.

**Pull request merged**
